version: 2

build:
  apt_packages:
    - libssl-dev
    - libcurl4-openssl-dev
    - libgdal-dev

sphinx:
   configuration: docs/source/conf.py

python:
   install:
   - requirements: requirements.txt
