version: 2

build:
  apt_packages:
    - libssl-dev
    - libcurl4-openssl-dev
    - python3-dev
    - gdal-bin
    - python3-gdal
    - python-gdal 
    - libgdal-dev 
    - g++
   
    

sphinx:
   configuration: docs/source/conf.py

python:
   install:
   - requirements: requirements.txt
