version: 2

build:
  apt_packages:
    - libssl-dev
    - libcurl4-openssl-dev
    - python3-dev

sphinx:
   configuration: docs/source/conf.py

python:
   version: 3.8
   install:
   - requirements: requirements.txt
