version: 2

build:
  apt_packages:
    - libssl-dev
    - libcurl4-openssl-dev
    - python3-dev
    - libgdal20
    - libproj12
   
    

sphinx:
   configuration: docs/source/conf.py

python:
   install:
   - requirements: requirements.txt
